# Generated by Django 4.2.20 on 2025-04-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='total_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
